server:
  port: 8100


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka

spring:
  application:
    name: trading-index
    
#¿ªÆô½µ¼¶
feign:
  hystrix:
    enabled: true

